use uuid to avoid conflicts

diff --git a/thefly b/thefly
--- a/thefly
+++ b/thefly
@@ -3,22 +3,30 @@
 case "$1" in
 install|loginshell)
     unset _floaded
-    mkdir -p "$_fenvdir/.fly.d"
+    (umask 077;mkdir -p "$_fenvdir/.fly.d/plugins")
     [ -f "$_fenvdir/.fly.d/.flyrc" ] || touch "$_fenvdir/.fly.d/.flyrc"
+    [ -f "$_fenvdir/.fly.d/.flyuuid" ] || uuidgen >"$_fenvdir/.fly.d/.flyuuid"
+    echo "TheFly: install in $_fenvdir/.fly.d/fly" >&2
+    echo "TheFly: Put in your shell profile to load thefly/plugins at login:" >&2
+    echo "TheFly:   source $_fenvdir/.fly.d/fly source" >&2
+    echo "TheFly: To add shell pluggins from github use:" >&2
+    echo "TheFly:   fly add <git owner>/<repo>" >&2
     ;;
 *)  echo "usage: source thefly [install|remote]"
-    return
+    return 1
     ;;
 esac
 
 cat - >"$_fenvdir/.fly.d/fly" <<'EOFLY' && . "$_fenvdir/.fly.d/fly"
 [ "$_floaded" ] && return
-#echo "the fly !!!"
+echo "Bzzz Bzzz !!!" >&2
 _floaded=1
 : "${_fenvdir:=$HOME}"
 : "${_fgithub=https://github.com}"
 : "${FLY_USER_RC=true}"
 : "${FLY_ETC_RC=true}"
+: "${_fuuid:=$(cat "$_fenvdir/.fly.d/.flyuuid" 2>/dev/null || uuidgen)}"
+: "${_ftmpdir:="/tmp/.fly.\$USER.$_fuuid"}"
 
 function _fshell
 {
@@ -40,20 +48,33 @@ function _fpackage
 
 function _fxpackage
 {
-    printf %s 'umask 077;mkdir -p "/tmp/.fly.$USER";tar xzf - -C "/tmp/.fly.$USER"'
+    printf '%s;' 'umask 077' 'mkdir -p "'"$_ftmpdir"'"'
+    #printf '%s;' '! chmod 700 "'"$_ftmpdir"'" && echo "Not owner of '"$_ftmpdir"'. Abort >&2" && exit 1'
+    printf '%s' 'tar xzf - -C "'"$_ftmpdir"'"'
+}
+
+function _fzsh_glob
+{
+    [ "$FLY_SHELL" = "zsh" ] || return
+    case "$1" in
+    fix)   [[ ! -o nonomatch ]] && _fzsh_nonomatch=1 && setopt nonomatch;;
+    reset) [ "$_fzsh_nomatch" ] && unset _fzsh_nonomatch && unsetopt nonomatch;;
+    esac
 }
 
 function _fsource_plugins
 {
-    typeset p="$1" plugin
+    typeset p="$1" plugin plugindir="$_fenvdir/.fly.d/plugins"
 
     [ -r "$_fenvdir/.fly.d/.flyrc" ] && . "$_fenvdir/.fly.d/.flyrc"
     [ -r "$_fenvdir/.fly.d/.flyrc.$FLY_SHELL" ] && . "$_fenvdir/.fly.d/.flyrc.$FLY_SHELL"
-    for plugin in $([ "$p" ] && ls "$_fenvdir/.fly.d/$p/"*.plugin."$FLY_SHELL" 2>/dev/null || \
-                                ls "$_fenvdir/.fly.d/"*/*.plugin."$FLY_SHELL" 2>/dev/null)
+    _fzsh_glob fix
+    for plugin in $([ "$p" ] && ls -- "$plugindir/$p/"*.plugin."$FLY_SHELL" 2>/dev/null || \
+                                ls -- "$plugindir/"*/*.plugin."$FLY_SHELL" 2>/dev/null)
     do
         \cd "${plugin%/*}" && { . "$plugin"; \cd "$OLDPWD"; }
     done
+    _fzsh_glob reset
 }
 
 function _fsource_profile_bash
@@ -121,26 +142,21 @@ function _flogin_rc
 
 function fsudo
 {
-    typeset user=${1:-root}
+    typeset user=${1:-root} 
     _fpackage |sudo -H -u "$user" $FLY_SHELL -c "$(_fxpackage)" || return $?
-    sudo -H -u "$user" -i FLY_USER_RC="$FLY_USER_RC" FLY_ETC_RC="$FLY_ETC_RC" _fdestshell="$_fdestshell" . /tmp/.fly.$user/.fly.d/fly loginshell /tmp/.fly.$user
+    sudo -H -u "$user" -i FLY_USER_RC="$FLY_USER_RC" FLY_ETC_RC="$FLY_ETC_RC" _fdestshell="$_fdestshell" "_fuuid=$_fuuid" . "$_ftmpdir/.fly.d/fly" loginshell "$_ftmpdir"
 }
 
 function _fssh_cmd
 {
-    typeset destdir='/tmp/.fly.$USER' b64opt
+    typeset b64opt
     echo ok |base64 -w0 >/dev/null 2>&1 && b64opt='-w0'
     cat - <<EOF
-umask 077
-mkdir -p "$destdir"
-! chmod 700 "$destdir" && echo "Not owner of $destdir. Abort" && exit 1
-cd "$destdir"
-echo $(_fpackage |base64 $b64opt) |base64 -d |tar xzf -
-[ $? != 0 ] && echo "Unpack env failed. Abort." && exit 1
+echo $(_fpackage |base64 $b64opt) |base64 -d |($(_fxpackage))
 _fdestshell="$_fdestshell"
 FLY_USER_RC="$FLY_USER_RC"
 FLY_ETC_RC="$FLY_ETC_RC"
-. ./.fly.d/fly loginshell $destdir
+_fuuid="$_fuuid" . "$_ftmpdir/.fly.d/fly" loginshell "$_ftmpdir"
 EOF
 }
 
@@ -178,7 +194,7 @@ EOF
 function fssh2
 {
     _fpackage | ssh -o LogLevel=Error "$@" "$(_fxpackage)" || return $?
-    ssh "$@" -t '. /tmp/.fly.$USER/.fly.d/fly loginshell /tmp/.fly.$USER'
+    ssh "$@" -t '. '"$_ftmpdir"'/.fly.d/fly loginshell '"$_ftmpdir"''
 }
 
 
@@ -187,23 +203,27 @@ function fly
     typeset plugin
     case "$1" in
     add)
-        mkdir -p "$_fenvdir/.fly.d"
-        (\cd "$_fenvdir/.fly.d" && git clone "$_fgithub/$2")
+        (umask 077;mkdir -p "$_fenvdir/.fly.d/plugins")
+        (\cd "$_fenvdir/.fly.d/plugins" && git clone "$_fgithub/$2")
         _fsource_plugins "${2#*/}"
     ;;
     update)
         [ ! "$2" ] && echo "usage: fly update <plugin>" && return 1 
-        (\cd "$_fenvdir/.fly.d/${2#*/}" && git pull origin "$(sed -e 's#.*/##' .git/HEAD)")
+        (\cd "$_fenvdir/.fly.d/plugins/${2#*/}" && git pull origin "$(sed -e 's#.*/##' .git/HEAD)")
         _fsource_plugins "${2#*/}"
     ;;
     updateall)
-        for plugin in $(ls -d "$_fenvdir/.fly.d"/*/.git) ;do
+        _fzsh_glob fix
+        for plugin in $(ls -d "$_fenvdir/.fly.d/plugins"/*/.git) ;do
             (\cd "$plugin/.." && git pull origin "$(sed -e 's#.*/##' .git/HEAD)")
         done
+        _fzsh_glob reset
         _fsource_plugins
     ;;
     list)
-        (\cd "$_fenvdir/.fly.d" && ls -1 -- */*.plugin.bash)
+        _fzsh_glob fix
+        (\cd "$_fenvdir/.fly.d/plugins" && ls -1 -- */*.plugin.$FLY_SHELL)
+        _fzsh_glob reset
     ;;
     source)
         _fsource_plugins
